[package]
name = "photo-server"
version = "0.1.0"
authors = ["Bjorn Arnholtz <bjorn.arnholtz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.1.0"
actix-cors = "0.4.1"
env_logger = "0.7.1"
serde = "1.0.116"
serde_json = "1.0.58"
serde_derive = "1.0.116"
juniper = "0.14.2"
argh = "0.1.3"
tokio = { version = "0.3.2", features = ['rt'] }
warp = "0.2.5"
