[package]
name = "photo-server"
version = "0.1.0"
authors = ["Bjorn Arnholtz <bjorn.arnholtz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 'z'
lto = true
panic="abort"
codegen-units = 1

[dependencies]
rand = "0.8.1"
bs58 = "0.4.0"

[dependencies.chrono]
version = "0.4.19"
default-features = false

[dependencies.serde]
version = "1.0.118"
default-features = false

[dependencies.serde_json]
version = "1.0.61"
default-features = false

[dependencies.serde_derive]
version = "1.0.118"
default-features = false

[dependencies.argh]
version = "0.1.4"
default-features = false

[dependencies.tokio]
version = "1.0.1"
default-features = false
features = ['rt']

[dependencies.tide]
version = "0.15.0"
default-features = false
features=['h1-server']
